### PR TITLE
Resolve #57 Slack Notifications

### PR DESCRIPTION
**Pull request by mzagaja**
* Notify slack when we get a new submission saved.

### CODE REVIEW

**Comment by atomtay** [comment]
This feels like a coffee-hasn't-sunk-in-yet problem, but: when I try to cURL in this test form submission:
```
curl -X "POST" "localhost:3000/form_submissions" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "form_submission": {
    "zo_usety": "0",
    "maxflrs": 2,
    "gen_coms": "The endzone!",
    "far": 0.59,
    "resolved": 0,
    "zo_name": "Test Zone",
    "zo_usede": "Filler text",
    "multifam": 0,
    "minlotsize": 50,
    "pctlotcov": 0.1,
    "view_src": 0,
    "maxdu": 2,
    "lapdu": 500,
    "maxheight": 23,
    "dupac": 2,
    "email": "devnull@mapc.org"
  }
}'
```

I get this error:
```
LoadError (cannot load such file -- faraday):
  
app/models/form_submission.rb:1:in `<main>'
```

I've `bundle install`'d so faraday should be there, not sure what's up.

**Review by atomtay — CHANGES_REQUESTED** [review]
It was a lack-of-coffee problem after all: faraday is available in the `Gemfile.lock`, but not in the `Gemfile`. If we added something new and `bundle install`'d, we'd lose faraday again. I added it into my Gemfile locally and it did the trick, so toss that in and we're good to go.

**Comment by mzagaja** [comment]
Weird that the Gemfile update didn't push. Must have been a gremlin. I pushed an amendment with it, and hopefully that fixes this.

**Comment by atomtay** [comment]
Looks good!

**Pull request merged**
